services:
  keycloak:
    build: ./keycloak
    ports:
      - "${KEYCLOAK_PORT}:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${POSTGRES_LOCAL_USER}
      KC_DB_PASSWORD: ${POSTGRES_LOCAL_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    command: ["start-dev"]
    volumes:
      - ./keycloak/data/export:/opt/keycloak/data/export
