apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mrp-service.fullname" . }}
  labels:
    {{- include "mrp-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mrp-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mrp-service.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: create-database
          image: postgres:latest
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          command:
            - sh
            - -c
            - |
              psql -h postgres -U postgres -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = '{{ .Values.spring.datasource.database }}'" | grep -q 1 || psql -h postgres -U postgres -d postgres -c "CREATE DATABASE {{ .Values.spring.datasource.database }}"
      containers:
        - name: {{ include "mrp-service.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profile }}"
            - name: SERVER_PORT
              value: "{{ .Values.service.port }}"
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.spring.datasource.url }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
