spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

services:
    master-data-service:
        name: master-data-service
        url: ${MASTER_DATA_SERVICE_URL}
    user-service:
        name: user-service
        url: ${USER_SERVICE_URL}
