CREATE TABLE cost_centers (
    id BIGSERIAL PRIMARY KEY,

    code VARCHAR(25) NOT NULL UNIQUE,

    name VARCHAR(255) NOT NULL,

    description TEXT,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
